title: Oskari Mantere
description: Notes on software, systems, and building things.
email: osku.mantere@gmail.com
github_username: oskrim
url: "https://oskrim.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
