title: Oskari Mantere
description: Software and systems
email: osku.mantere@gmail.com
github_username: oskrim
x_username: agi_asap
url: "https://oskrim.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
